# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_control_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cserver_control_message.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"J\n\x14\x43\x61meraControlCommand\x12\x1c\n\njoints_vel\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x14\n\x0c\x66ocal_length\x18\x02 \x01(\x01\"(\n\x0fSettingsCommand\x12\x15\n\radaptive_rate\x18\x01 \x01(\x08\"D\n\rFrankaCommand\x12\x1e\n\x0c\x65\x66\x66\x65\x63tor_pos\x18\x01 \x01(\x0b\x32\x08.Vector3\x12\x13\n\x0bshow_marker\x18\x02 \x01(\x08\"\xb2\x01\n\x14ServerControlMessage\x12\x37\n\x16\x63\x61mera_control_command\x18\x01 \x01(\x0b\x32\x15.CameraControlCommandH\x00\x12,\n\x10settings_command\x18\x02 \x01(\x0b\x32\x10.SettingsCommandH\x00\x12(\n\x0e\x66ranka_command\x18\x03 \x01(\x0b\x32\x0e.FrankaCommandH\x00\x42\t\n\x07\x63ommandb\x06proto3')



_VECTOR3 = DESCRIPTOR.message_types_by_name['Vector3']
_CAMERACONTROLCOMMAND = DESCRIPTOR.message_types_by_name['CameraControlCommand']
_SETTINGSCOMMAND = DESCRIPTOR.message_types_by_name['SettingsCommand']
_FRANKACOMMAND = DESCRIPTOR.message_types_by_name['FrankaCommand']
_SERVERCONTROLMESSAGE = DESCRIPTOR.message_types_by_name['ServerControlMessage']
Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3,
  '__module__' : 'server_control_message_pb2'
  # @@protoc_insertion_point(class_scope:Vector3)
  })
_sym_db.RegisterMessage(Vector3)

CameraControlCommand = _reflection.GeneratedProtocolMessageType('CameraControlCommand', (_message.Message,), {
  'DESCRIPTOR' : _CAMERACONTROLCOMMAND,
  '__module__' : 'server_control_message_pb2'
  # @@protoc_insertion_point(class_scope:CameraControlCommand)
  })
_sym_db.RegisterMessage(CameraControlCommand)

SettingsCommand = _reflection.GeneratedProtocolMessageType('SettingsCommand', (_message.Message,), {
  'DESCRIPTOR' : _SETTINGSCOMMAND,
  '__module__' : 'server_control_message_pb2'
  # @@protoc_insertion_point(class_scope:SettingsCommand)
  })
_sym_db.RegisterMessage(SettingsCommand)

FrankaCommand = _reflection.GeneratedProtocolMessageType('FrankaCommand', (_message.Message,), {
  'DESCRIPTOR' : _FRANKACOMMAND,
  '__module__' : 'server_control_message_pb2'
  # @@protoc_insertion_point(class_scope:FrankaCommand)
  })
_sym_db.RegisterMessage(FrankaCommand)

ServerControlMessage = _reflection.GeneratedProtocolMessageType('ServerControlMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERCONTROLMESSAGE,
  '__module__' : 'server_control_message_pb2'
  # @@protoc_insertion_point(class_scope:ServerControlMessage)
  })
_sym_db.RegisterMessage(ServerControlMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3._serialized_start=32
  _VECTOR3._serialized_end=74
  _CAMERACONTROLCOMMAND._serialized_start=76
  _CAMERACONTROLCOMMAND._serialized_end=150
  _SETTINGSCOMMAND._serialized_start=152
  _SETTINGSCOMMAND._serialized_end=192
  _FRANKACOMMAND._serialized_start=194
  _FRANKACOMMAND._serialized_end=262
  _SERVERCONTROLMESSAGE._serialized_start=265
  _SERVERCONTROLMESSAGE._serialized_end=443
# @@protoc_insertion_point(module_scope)
